### ISSUE TITLE
errors out in fit_transform

### ISSUE THREAD

**Issue by chngl** [MaartenGr/BERTopic#123]
Hi Maarten, Thanks for building this awesome library, it makes our life so much easier to run topic modeling. 

We've been using it in our project and it has been running pretty well. However, today we ran into an issue when calling fit_transform, here's the stack trace:

```
Traceback (most recent call last):
  File "__run_par_main__.py", line 9, in <module>
    __invoke_main()
  File "__run_par_main__.py", line 8, in __invoke_main
    runpy._run_module_as_main('peopleinsights.bert_topic_modeling.py.main', False)
  File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/par_unpack.30374.6a6edd8729432e3d237fbe42b78e97dc/peopleinsights/bert_topic_modeling/py/main.py", line 126, in <module>
    docs_topic, probs = topic_model.fit_transform(docs)
  File "/tmp/par_unpack.30374.6a6edd8729432e3d237fbe42b78e97dc/bertopic/_bertopic.py", line 284, in fit_transform
    documents, probabilities = self._cluster_embeddings(umap_embeddings, documents)
  File "/tmp/par_unpack.30374.6a6edd8729432e3d237fbe42b78e97dc/bertopic/_bertopic.py", line 1123, in _cluster_embeddings
    self.hdbscan_model.fit(umap_embeddings)
  File "/tmp/par_unpack.30374.6a6edd8729432e3d237fbe42b78e97dc/hdbscan/hdbscan_.py", line 915, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "/tmp/par_unpack.30374.6a6edd8729432e3d237fbe42b78e97dc/hdbscan/hdbscan_.py", line 606, in hdbscan
    (single_linkage_tree, result_min_span_tree) = memory.cache(
  File "/tmp/par_unpack.30374.6a6edd8729432e3d237fbe42b78e97dc/joblib/memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "/tmp/par_unpack.30374.6a6edd8729432e3d237fbe42b78e97dc/hdbscan/hdbscan_.py", line 275, in _hdbscan_boruvka_kdtree
    alg = KDTreeBoruvkaAlgorithm(tree, min_samples, metric=metric,
  File "hdbscan/_hdbscan_boruvka.pyx", line 375, in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm.__init__
  File "hdbscan/_hdbscan_boruvka.pyx", line 411, in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm._compute_bounds
  File "/tmp/par_unpack.30374.6a6edd8729432e3d237fbe42b78e97dc/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/tmp/par_unpack.30374.6a6edd8729432e3d237fbe42b78e97dc/joblib/parallel.py", line 831, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "hdbscan/_hdbscan_boruvka.pyx", line 412, in genexpr
TypeError: delayed() got an unexpected keyword argument 'check_pickle'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'joblib'
```

Not sure if this is related to the size of the data set we pass in (50K sentences, our largest data set so far). Tried low_memory flag, but didn't solve the problem. 

Could you please help take a look?

Thank you in advance.

**Comment by MaartenGr** [comment]
Did you change environments when running this code? It seems like you have the incorrect version of the joblib package. Which versions joblib and BERTopic do you have installed?

Having said that, it might be worthwhile to start from a fresh environment and install the newest version of BERTopic. In earlier versions of HDBSCAN there was an issue with joblib 1.0.0 which should be fixed in the newest versions of HDBSCAN. So starting from a fresh environment should fix this issue.

**Comment by chngl** [comment]
Thanks for getting back to me so quickly. 
No we didn't change environment when running the code. We are using BERTopic 0.6.0. We'll try to update to BERTopic 0.7.0 to see if it solves the issue!

Just a side note, this issue seems to only happen when we run topic modeling on slightly large data set. Does this suggest anything?

**Comment by MaartenGr** [comment]
Although a slightly large data set may trigger this, it is a bug specific to a new version of joblib that interacts poorly with specific versions of HDBSCAN. You can find more about that [here](https://github.com/scikit-learn-contrib/hdbscan/issues/436).

**Comment by chngl** [comment]
Hi Maarten, looks like the issue is still happening even after we upgraded to the newest version of BERTopic. Is there anything else I should try? 

Also, what's the largest data set you've ever run BERTopic against? I noticed that, the error happens after about 1 hour into the execution. The data set is about 50k sentences. 

Thank you in advance.
